

parameters:
    ft_config.enabled:  false # gets overridden
    ft_config.class:    UKHomeOffice\Bundle\GovUKFTBundle\Config
    ft_config.title:    "Report me a lost or stolen passport"
    ft_config.theme:    global
    ft_config.breadcrumb:
        - 
          - Passports, travel and living abroad
          - https://www.gov.uk/browse/abroad
        -
          - Passports
          - https://www.gov.uk/browse/abroad/passports
        -  
          - Report a lost or stolen passport
          - https://www.gov.uk/report-a-lost-or-stolen-passport
    ft_config.sidebar:
        Passports:
          - 
            - Get a passport for your child
            - https://www.gov.uk/get-a-child-passport
          -
            - Get a passport urgently
            - https://www.gov.uk/get-a-passport-urgently
          -  
            - Renew or replace your adult passport
            - https://www.gov.uk/renew-adult-passport
          -
            - More
            - https://www.gov.uk/browse/abroad/passports
            - Passports
        Elsewhere on GOV.UK:
          -  
            - Contact the po-lice
            - https://www.gov.uk/contact-police
    ft_config.hide_breadcrumb: false
    ft_config.hide_sidebar: true



services:
    ft_config:
        class:          "%ft_config.class%"
        arguments:
          - "%ft_config.title%"
          - "%ft_config.theme%"
          - "%ft_config.breadcrumb%"
          - "%ft_config.sidebar%"
          - "%ft_config.hide_breadcrumb%"
          - "%ft_config.hide_sidebar%"


